package ui.form_items

object CustomViewUtils{
    const val FIELD_TYPE_TEXT = "Text"
    const val FIELD_TYPE_DATETIME = "DateTime"
    const val FIELD_TYPE_RADIO = "Radio"
    const val FIELD_TYPE_CHECKBOX = "Checkbox"
    const val FIELD_TYPE_DROPDOWN = "DropDown"
    const val FIELD_TYPE_TEXTAREA = "TextArea"
    const val FIELD_TYPE_MULTISELECTLIST = "MultiSelectList"
    const val FIELD_TYPE_EMAIL = "Email"
    const val FIELD_TYPE_PHONENUMBER = "PhoneNumber"
    const val FIELD_TYPE_CASE_CONTACT = "CaseContact"
    const val FIELD_TYPE_SERVICE_LOCATION = "ServiceLocation"
    const val FIELD_TYPE_FILE = "File"
    const val FIELD_TYPE_FILE_UPLOAD_V2 = "FileUploadV2"
    const val FIELD_TYPE_CASE_COMMENT = "CaseComment"
    const val FIELD_CASE_PROVIDER = "CaseProvider"
    const val FIELD_CASE_ASSIGNEE = "CaseAssignee"
    const val FIELD_USER_LIST_DROPDOWN = "UserListDropDown"
    const val FIELD_ROLE_LIST_DROPDOWN = "RoleListDropDown"
    const val FIELD_ROLE_LIST_MULTISELECT = "RoleListMultiSelect"
    const val FIELD_USER_LIST_MULTISELECT = "UserListMultiSelect"
    const val FIELD_TYPE_RICH_TEXT = "Richtext"
    const val FIELD_TYPE_SINGLE_CHECK_BOX = "SingleCheckbox"
    const val FIELD_TYPE_CASE_TRANSFER = "CaseTransfer"
    const val FIELD_TYPE_GRID_VIEW = "GridView"
    const val FIELD_TYPE_GRID_ROW = "GridRow"
    const val FIELD_TYPE_SERVICE_LOCATION_ESRI = "ServiceLocationESRI"
    const val FIELD_TYPE_CANVAS = "Canvas"
    const val FIELD_TYPE_SERVICE_LOCATION_V2 = "ServiceLocationV2"
    const val FIELD_TYPE_COMPUTED = "Computed"
    const val FIELD_TYPE_CASE_TAGS = "CaseTags"
    const val FIELD_TYPE_CASE_RESOLUTION = "CaseResolution"
    const val FIELD_TYPE_SERVICE_LOCATION_GIS = "ServiceLocationGIS"
    const val FIELD_TYPE_SERVICE_LOCATION_GIS_V3 = "ServiceLocationGISV3"
    const val FIELD_TYPE_SINGLE_SELECT_DROPDOWN = "SingleSelectUserDropDown"
    const val FIELD_TYPE_SERVICE_LOCATION_V3 = "ServiceLocationV3"
    const val FIELD_TYPE_CONDITIONAL_FORM_SUBMIT = "ConditionalFormSubmit"
    const val FIELD_TYPE_SERVICE_ADDRESS_V2 = "ServiceAddressv2"
    const val FIELD_TYPE_TILE_VIEW = "TileView"
    const val FIELD_TYPE_ACCORDIAN = "Accordian"

}
